---
on:
- push
- pull_request
name: ci

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Setup pnpm
        uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.8.0

      - name: print node version
        run: |
          node -v
          npm -v
          pnpm -v

      - name: install dependencies
        run: pnpm i

      - name: build typescript
        run: pnpm run build


  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Setup pnpm
        uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.8.0

      - name: print node version
        run: |
          node -v
          npm -v
          pnpm -v

      - name: install dependencies
        run: pnpm i

      - name: lint typescript
        run: pnpm run lint
